//! Export Bifrost hosts as an ssh config file.
//!
//! The export goes to its own file, `~/.ssh/bifrost_config` by default, and
//! never touches `~/.ssh/config`. To use the hosts, the user adds this line
//! near the top of their own `~/.ssh/config`:
//!
//! ```text
//! Include ~/.ssh/bifrost_config
//! ```
//!
//! What is exported: `HostName`, `User`, `Port`, `IdentityFile` (with
//! `IdentitiesOnly yes`), `ProxyJump`, `LocalForward`, `RemoteForward` (both
//! bound to `127.0.0.1`) and `ForwardAgent yes` when enabled. Notes, tags and
//! favorites stay in Bifrost. `ProxyCommand` and `LocalCommand` are never
//! written.
//!
//! # ProxyJump limitation (0.1.0)
//!
//! A jump host is written as `user@host:port` taken from the Bifrost store,
//! and a jump host that itself has a jump host is written as a comma-separated
//! chain, first hop first (at most [`MAX_JUMP_HOPS`](crate::domain::jump::MAX_JUMP_HOPS)
//! hops). The jump host's own
//! `IdentityFile` is not part of that: its key must be in `ssh-agent` or be one
//! of ssh's default keys.
//!
//! Every value is validated again before it is written, and values are quoted
//! and escaped for ssh_config, so nothing in a host can start a new directive.

use std::fmt;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use crate::domain::jump::jump_chain;
use crate::domain::validate::{self, Field, ValidationError};
use crate::domain::{Host, Hosts};
use crate::store::fsutil;
use crate::sysenv::{self, Env, Platform};
use crate::text::escape_control;

/// The first line of every exported file. A file that does not start with it
/// is not overwritten.
pub const GENERATED_HEADER: &str = "# Generated by Bifrost";

/// File name of the default export inside `~/.ssh`.
pub const EXPORT_FILE_NAME: &str = "bifrost_config";

#[derive(Debug)]
pub enum ExportError {
    NoHome,
    /// A host does not satisfy the validation rules (including jump chains).
    Invalid(ValidationError),
    /// A value contains characters that cannot be written to the file safely.
    /// Validation should make this unreachable; it is checked again here
    /// because this is the last step before untrusted-looking text becomes
    /// ssh configuration.
    UnsafeValue {
        host: String,
        field: &'static str,
    },
    /// The target exists but was not generated by Bifrost.
    NotGenerated(PathBuf),
    /// The target is an ssh `config` file, which Bifrost never writes.
    ProtectedTarget(PathBuf),
    Io {
        action: &'static str,
        path: PathBuf,
        source: io::Error,
    },
}

impl fmt::Display for ExportError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ExportError::NoHome => f.write_str(
                "Could not find your home directory, so ~/.ssh/bifrost_config cannot be located.",
            ),
            ExportError::Invalid(err) => write!(f, "Cannot export: {err}"),
            ExportError::UnsafeValue { host, field } => write!(
                f,
                "Cannot export host '{}': its {field} contains characters that cannot be \
                 written safely.",
                escape_control(host)
            ),
            ExportError::NotGenerated(path) => write!(
                f,
                "{} already exists and was not generated by Bifrost, so it was left alone. \
                 Choose another file or move it away.",
                path.display()
            ),
            ExportError::ProtectedTarget(path) => write!(
                f,
                "{} looks like an ssh config file. Bifrost never writes to those; export to a \
                 separate file such as ~/.ssh/{EXPORT_FILE_NAME}.",
                path.display()
            ),
            ExportError::Io {
                action,
                path,
                source,
            } => write!(f, "Could not {action} {}: {source}", path.display()),
        }
    }
}

impl std::error::Error for ExportError {}

/// `~/.ssh/bifrost_config` (`%USERPROFILE%\.ssh\bifrost_config` on Windows).
pub fn default_export_path(platform: Platform, env: Env<'_>) -> Result<PathBuf, ExportError> {
    sysenv::home_dir(platform, env)
        .map(|home| home.join(".ssh").join(EXPORT_FILE_NAME))
        .ok_or(ExportError::NoHome)
}

/// Renders the ssh config text for `hosts`.
pub fn render(hosts: &Hosts) -> Result<String, ExportError> {
    render_slice(hosts.as_slice())
}

/// Renders and writes the export to `target`, user-only, atomically.
///
/// Refuses to write over a file that Bifrost did not generate, or to anything
/// named `config`. Missing parent directories are created user-only.
pub fn export_to(hosts: &Hosts, target: &Path) -> Result<(), ExportError> {
    let content = render(hosts)?;

    let is_ssh_config = target
        .file_name()
        .is_some_and(|name| name.to_string_lossy().eq_ignore_ascii_case("config"));
    if is_ssh_config {
        return Err(ExportError::ProtectedTarget(target.to_path_buf()));
    }

    match fs::read(target) {
        Ok(existing) if !existing.starts_with(GENERATED_HEADER.as_bytes()) => {
            return Err(ExportError::NotGenerated(target.to_path_buf()));
        }
        Ok(_) => {}
        Err(err) if err.kind() == io::ErrorKind::NotFound => {}
        Err(source) => {
            return Err(ExportError::Io {
                action: "read",
                path: target.to_path_buf(),
                source,
            });
        }
    }

    if let Some(parent) = target.parent().filter(|p| !p.as_os_str().is_empty()) {
        fsutil::ensure_private_dir(parent).map_err(|source| ExportError::Io {
            action: "create the directory",
            path: parent.to_path_buf(),
            source,
        })?;
    }
    fsutil::atomic_write(target, content.as_bytes()).map_err(|source| ExportError::Io {
        action: "write",
        path: target.to_path_buf(),
        source,
    })
}

fn render_slice(hosts: &[Host]) -> Result<String, ExportError> {
    // Same rules as when hosts are added, so a value that could never have
    // been saved can never be written either. This also guarantees that no
    // value holds a control character and that every jump chain resolves.
    validate::check_hosts(hosts).map_err(ExportError::Invalid)?;

    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str(". Do not edit: changes are lost on the next export.\n");
    out.push_str("# To use these hosts, add this line near the top of ~/.ssh/config:\n");
    out.push_str(&format!("#   Include ~/.ssh/{EXPORT_FILE_NAME}\n"));
    for (index, host) in hosts.iter().enumerate() {
        let chain = jump_chain(hosts, host).map_err(|err| {
            ExportError::Invalid(
                ValidationError::new(Field::ProxyJump, err.to_string())
                    .with_host(index, &host.name),
            )
        })?;
        out.push('\n');
        render_host(&mut out, host, &chain)?;
    }
    Ok(out)
}

/// Appends one `Host` block. `chain` is the host's jump chain, first hop first.
///
/// Every value goes through [`arg`] or [`quote`], which refuse values that
/// could break out of their directive.
fn render_host(out: &mut String, host: &Host, chain: &[&Host]) -> Result<(), ExportError> {
    let unsafe_value = |field: &'static str| ExportError::UnsafeValue {
        host: host.name.clone(),
        field,
    };
    let word = |field: &'static str, value: &str| arg(value).map_err(|_| unsafe_value(field));

    out.push_str(&format!("Host {}\n", word("name", &host.name)?));
    out.push_str(&format!(
        "    HostName {}\n",
        word("hostname", &host.hostname)?
    ));
    if let Some(user) = &host.user {
        out.push_str(&format!("    User {}\n", word("user", user)?));
    }
    if let Some(port) = host.port {
        out.push_str(&format!("    Port {port}\n"));
    }
    if let Some(identity_file) = &host.identity_file {
        let quoted = quote(identity_file).map_err(|_| unsafe_value("identity file"))?;
        out.push_str(&format!("    IdentityFile {quoted}\n"));
        out.push_str("    IdentitiesOnly yes\n");
    }
    if !chain.is_empty() {
        let hops: Vec<String> = chain.iter().map(|hop| jump_spec(hop)).collect();
        out.push_str(&format!(
            "    ProxyJump {}\n",
            word("jump host", &hops.join(","))?
        ));
    }
    for (keyword, field, forwards) in [
        ("LocalForward", "local forward", &host.local_forwards),
        ("RemoteForward", "remote forward", &host.remote_forwards),
    ] {
        for forward in forwards {
            out.push_str(&format!(
                "    {keyword} {} {}\n",
                word(field, &endpoint("127.0.0.1", forward.listen_port))?,
                word(field, &endpoint(&forward.dest_host, forward.dest_port))?
            ));
        }
    }
    if host.forward_agent {
        out.push_str("    ForwardAgent yes\n");
    }
    Ok(())
}

/// `[user@]host:port` for one hop of a ProxyJump, with the port always explicit.
pub(super) fn jump_spec(hop: &Host) -> String {
    let endpoint = endpoint(&hop.hostname, hop.port.unwrap_or(22));
    match &hop.user {
        Some(user) => format!("{user}@{endpoint}"),
        None => endpoint,
    }
}

/// `host:port`, with brackets around IPv6 addresses.
pub(super) fn endpoint(host: &str, port: u16) -> String {
    if host.contains(':') {
        format!("[{host}]:{port}")
    } else {
        format!("{host}:{port}")
    }
}

/// A value that holds a control character or line break, which could end the
/// directive it is written into and start a new one.
#[derive(Debug, PartialEq, Eq)]
struct ControlCharacter;

/// A value as one ssh_config argument: bare when it only has safe characters,
/// otherwise quoted. Fails for control characters and line breaks, in release
/// builds too.
fn arg(value: &str) -> Result<String, ControlCharacter> {
    let bare = !value.is_empty()
        && value
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || "._-@:/~+,[]".contains(c));
    if bare {
        Ok(value.to_string())
    } else {
        quote(value)
    }
}

/// Always-quoted form. Backslash and double quote are escaped for ssh's
/// argument splitting, and `%` is doubled because ssh expands `%` tokens in
/// paths and jump specs. Fails for control characters and line breaks, in
/// release builds too: validated values never have them, but this check must
/// not depend on that.
fn quote(value: &str) -> Result<String, ControlCharacter> {
    if value.chars().any(char::is_control) {
        return Err(ControlCharacter);
    }
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for c in value.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '%' => out.push_str("%%"),
            c => out.push(c),
        }
    }
    out.push('"');
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::Forward;
    use crate::sysenv::testing::{abs, fake_env};

    type Mutation = Box<dyn Fn(&mut Host)>;

    fn host(name: &str, hostname: &str) -> Host {
        Host::new(name, hostname)
    }

    fn hosts(list: Vec<Host>) -> Hosts {
        Hosts::from_vec(list).expect("fixture should be valid")
    }

    fn forward(listen: u16, dest: &str, port: u16) -> Forward {
        Forward {
            listen_port: listen,
            dest_host: dest.into(),
            dest_port: port,
        }
    }

    /// Splits a line the way OpenSSH's argument splitter does: whitespace
    /// separates tokens, double quotes group, backslash escapes `\`, `"` and `'`.
    /// Then undoes `%%`, the only token ssh would expand.
    fn ssh_tokens(line: &str) -> Vec<String> {
        let mut tokens = Vec::new();
        let mut current = String::new();
        let mut started = false;
        let mut in_quotes = false;
        let mut chars = line.chars().peekable();
        while let Some(c) = chars.next() {
            match c {
                '\\' if matches!(chars.peek(), Some('\\' | '"' | '\'')) => {
                    current.push(chars.next().unwrap());
                    started = true;
                }
                '"' => {
                    in_quotes = !in_quotes;
                    started = true;
                }
                c if c.is_whitespace() && !in_quotes => {
                    if started {
                        tokens.push(std::mem::take(&mut current));
                        started = false;
                    }
                }
                c => {
                    current.push(c);
                    started = true;
                }
            }
        }
        assert!(!in_quotes, "unbalanced quotes in {line:?}");
        if started {
            tokens.push(current);
        }
        tokens.into_iter().map(|t| t.replace("%%", "%")).collect()
    }

    const ALLOWED_KEYWORDS: [&str; 10] = [
        "Host",
        "HostName",
        "User",
        "Port",
        "IdentityFile",
        "IdentitiesOnly",
        "ProxyJump",
        "LocalForward",
        "RemoteForward",
        "ForwardAgent",
    ];

    /// Every directive line must use a keyword Bifrost writes on purpose.
    fn assert_only_expected_directives(output: &str) {
        for line in output.lines() {
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') {
                continue;
            }
            let keyword = ssh_tokens(trimmed).remove(0);
            assert!(
                ALLOWED_KEYWORDS.contains(&keyword.as_str()),
                "unexpected directive in {line:?}"
            );
        }
    }

    #[test]
    fn renders_a_full_host() {
        let mut web = host("web", "web.example.com");
        web.user = Some("deploy".into());
        web.port = Some(2222);
        web.identity_file = Some("~/.ssh/id_ed25519".into());
        web.forward_agent = true;
        web.local_forwards = vec![forward(5433, "db.internal", 5432)];
        web.remote_forwards = vec![forward(9000, "localhost", 3000)];
        let text = render(&hosts(vec![web])).unwrap();
        assert_eq!(
            text,
            "# Generated by Bifrost. Do not edit: changes are lost on the next export.\n\
             # To use these hosts, add this line near the top of ~/.ssh/config:\n\
             #   Include ~/.ssh/bifrost_config\n\
             \n\
             Host web\n\
             \x20   HostName web.example.com\n\
             \x20   User deploy\n\
             \x20   Port 2222\n\
             \x20   IdentityFile \"~/.ssh/id_ed25519\"\n\
             \x20   IdentitiesOnly yes\n\
             \x20   LocalForward 127.0.0.1:5433 db.internal:5432\n\
             \x20   RemoteForward 127.0.0.1:9000 localhost:3000\n\
             \x20   ForwardAgent yes\n"
        );
        assert_only_expected_directives(&text);
    }

    #[test]
    fn minimal_hosts_only_write_what_is_set() {
        let text = render(&hosts(vec![host("a", "a.example.com")])).unwrap();
        assert!(
            text.ends_with("Host a\n    HostName a.example.com\n"),
            "{text}"
        );
        assert!(!text.contains("ForwardAgent"));
        assert!(!text.contains("IdentitiesOnly"));
    }

    #[test]
    fn empty_store_renders_only_the_header() {
        let text = render(&Hosts::new()).unwrap();
        assert!(text.starts_with(GENERATED_HEADER));
        assert!(!text.contains("Host "));
    }

    #[test]
    fn notes_tags_and_favorites_are_never_exported() {
        let mut web = host("web", "web.example.com");
        web.notes = Some("secret note: the root password is on a sticky".into());
        web.tags = vec!["confidential-tag".into()];
        web.favorite = true;
        let text = render(&hosts(vec![web])).unwrap();
        assert!(!text.contains("secret"));
        assert!(!text.contains("confidential-tag"));
        assert!(!text.to_ascii_lowercase().contains("favorite"));
    }

    #[test]
    fn proxy_jump_is_expanded_to_user_host_port() {
        let mut bastion = host("bastion", "bastion.example.com");
        bastion.user = Some("admin".into());
        bastion.port = Some(2200);
        let mut web = host("web", "10.0.0.5");
        web.proxy_jump = Some("bastion".into());
        let text = render(&hosts(vec![bastion, web])).unwrap();
        assert!(
            text.contains(
                "Host web\n    HostName 10.0.0.5\n    ProxyJump admin@bastion.example.com:2200\n"
            ),
            "{text}"
        );
    }

    #[test]
    fn proxy_jump_without_user_or_port_is_still_explicit_about_the_port() {
        let bastion = host("bastion", "bastion.example.com");
        let mut web = host("web", "10.0.0.5");
        web.proxy_jump = Some("bastion".into());
        let text = render(&hosts(vec![bastion, web])).unwrap();
        assert!(
            text.contains("    ProxyJump bastion.example.com:22\n"),
            "{text}"
        );
    }

    #[test]
    fn proxy_jump_chains_are_comma_separated_first_hop_first() {
        // web -> b -> a: ssh must connect to a first, then b, then web.
        let mut a = host("a", "a.example.com");
        a.user = Some("ua".into());
        let mut b = host("b", "b.example.com");
        b.user = Some("ub".into());
        b.port = Some(2222);
        b.proxy_jump = Some("a".into());
        let mut web = host("web", "web.example.com");
        web.proxy_jump = Some("b".into());
        let text = render(&hosts(vec![a, b, web])).unwrap();
        assert!(
            text.contains("Host web\n    HostName web.example.com\n    ProxyJump ua@a.example.com:22,ub@b.example.com:2222\n"),
            "{text}"
        );
        // The middle host is itself reached through `a`.
        assert!(text.contains("Host b\n    HostName b.example.com\n    User ub\n    Port 2222\n    ProxyJump ua@a.example.com:22\n"));
    }

    #[test]
    fn ipv6_addresses_are_bracketed_where_ssh_needs_it() {
        let mut bastion = host("bastion", "2001:db8::1");
        bastion.user = Some("admin".into());
        let mut web = host("web", "2001:db8::2");
        web.proxy_jump = Some("bastion".into());
        web.local_forwards = vec![forward(8080, "::1", 80)];
        let text = render(&hosts(vec![bastion, web])).unwrap();
        assert!(text.contains("    HostName 2001:db8::2\n"), "{text}");
        assert!(
            text.contains("    ProxyJump admin@[2001:db8::1]:22\n"),
            "{text}"
        );
        assert!(
            text.contains("    LocalForward 127.0.0.1:8080 [::1]:80\n"),
            "{text}"
        );
    }

    #[test]
    fn a_user_with_a_backslash_is_quoted_and_escaped() {
        let mut jump = host("jump", "jump.example.com");
        jump.user = Some("CORP\\admin".into());
        let mut web = host("web", "web.example.com");
        web.user = Some("CORP\\me".into());
        web.proxy_jump = Some("jump".into());
        let text = render(&hosts(vec![jump, web])).unwrap();
        assert!(text.contains("    User \"CORP\\\\me\"\n"), "{text}");
        assert!(
            text.contains("    ProxyJump \"CORP\\\\admin@jump.example.com:22\"\n"),
            "{text}"
        );
        // What ssh reads back is the original value.
        let line = text
            .lines()
            .find(|l| l.contains("User \"CORP\\\\me\""))
            .unwrap();
        assert_eq!(ssh_tokens(line), ["User", "CORP\\me"]);
    }

    #[test]
    fn identity_files_survive_quoting_exactly() {
        let nasty = [
            "~/.ssh/id_ed25519",
            "/home/me/my keys/id",
            "C:\\Users\\me\\.ssh\\id_ed25519",
            "/tmp/a\" ProxyCommand evil \"b",
            "/tmp/a\\\" ProxyCommand evil",
            "/tmp/100%/key",
            "/tmp/%d/%h/%u",
            "/tmp/it's",
            "/tmp/a#b",
            "/tmp/  double  space",
            "key with = sign",
            "/tmp/a\\\\b",
        ];
        for path in nasty {
            let mut web = host("web", "web.example.com");
            web.identity_file = Some(path.into());
            let text = render(&hosts(vec![web])).unwrap();
            assert_only_expected_directives(&text);
            let line = text
                .lines()
                .find(|l| l.trim_start().starts_with("IdentityFile"))
                .unwrap();
            assert_eq!(ssh_tokens(line), ["IdentityFile", path], "{line}");
        }
    }

    #[test]
    fn injection_attempts_are_rejected_before_anything_is_written() {
        let attempts: Vec<Mutation> = vec![
            Box::new(|h| h.name = "a\nProxyCommand id".into()),
            Box::new(|h| h.hostname = "h.example.com\n    ProxyCommand id".into()),
            Box::new(|h| h.hostname = "-oProxyCommand=id".into()),
            Box::new(|h| h.user = Some("u\nProxyCommand id".into())),
            Box::new(|h| h.user = Some("-oProxyCommand=id".into())),
            Box::new(|h| h.identity_file = Some("k\r\nProxyCommand id".into())),
            Box::new(|h| h.identity_file = Some("-oProxyCommand=id".into())),
            Box::new(|h| h.proxy_jump = Some("x\nProxyCommand id".into())),
            Box::new(|h| h.local_forwards.push(forward(1, "d\nProxyCommand id", 2))),
            Box::new(|h| h.remote_forwards.push(forward(1, "-oProxyCommand=id", 2))),
            Box::new(|h| h.name = "a b".into()),
            Box::new(|h| h.name = "*".into()),
        ];
        for (i, mutate) in attempts.iter().enumerate() {
            let mut candidate = host("ok", "ok.example.com");
            mutate(&mut candidate);
            assert!(
                matches!(render_slice(&[candidate]), Err(ExportError::Invalid(_))),
                "attempt {i} should be refused"
            );
        }
    }

    #[test]
    fn hosts_built_through_the_api_cannot_carry_injection() {
        let mut hosts = Hosts::new();
        let mut evil = host("evil", "evil.example.com");
        evil.identity_file = Some("k\nProxyCommand id".into());
        assert!(hosts.add(evil).is_err());
        assert!(hosts.is_empty());
        // Nothing to export but the header, and it is clean.
        assert_only_expected_directives(&render(&hosts).unwrap());
    }

    #[test]
    fn chains_longer_than_five_hops_are_refused_at_export_too() {
        let chain = |hops: usize| -> Vec<Host> {
            (0..=hops)
                .map(|i| {
                    let mut h = host(&format!("h{i}"), &format!("h{i}.example.com"));
                    if i < hops {
                        h.proxy_jump = Some(format!("h{}", i + 1));
                    }
                    h
                })
                .collect()
        };
        assert!(render_slice(&chain(5)).is_ok());
        let err = render_slice(&chain(6)).unwrap_err();
        assert!(matches!(err, ExportError::Invalid(_)));
        assert!(err.to_string().contains("at most 5 hops"), "{err}");
    }

    #[test]
    fn jump_cycles_are_refused_at_export() {
        let mut a = host("a", "a.example.com");
        a.proxy_jump = Some("b".into());
        let mut b = host("b", "b.example.com");
        b.proxy_jump = Some("a".into());
        let err = render_slice(&[a, b]).unwrap_err();
        assert!(err.to_string().contains("loop"), "{err}");
    }

    #[test]
    fn arg_quotes_only_when_needed() {
        assert_eq!(arg("plain-value").unwrap(), "plain-value");
        assert_eq!(arg("user@host:22").unwrap(), "user@host:22");
        assert_eq!(arg("").unwrap(), "\"\"");
        assert_eq!(arg("has space").unwrap(), "\"has space\"");
        assert_eq!(arg("a\"b").unwrap(), "\"a\\\"b\"");
        assert_eq!(arg("100%").unwrap(), "\"100%%\"");
        assert_eq!(quote("x").unwrap(), "\"x\"");
    }

    #[test]
    fn arg_and_quote_refuse_control_characters_themselves() {
        // Called directly, bypassing validation: this is the last line of
        // defense, and it must hold in release builds too.
        for malicious in [
            "a\nProxyCommand id",
            "a\r\nProxyCommand id",
            "key\"\nProxyCommand id",
            "tab\there",
            "nul\0byte",
            "esc\x1b[31m",
            "del\x7f",
            "nel\u{85}",
            "\n",
        ] {
            assert_eq!(arg(malicious), Err(ControlCharacter), "arg {malicious:?}");
            assert_eq!(
                quote(malicious),
                Err(ControlCharacter),
                "quote {malicious:?}"
            );
        }
        // Printable non-ASCII text is not a control character.
        assert_eq!(quote("clé").unwrap(), "\"clé\"");
    }

    #[test]
    fn render_host_refuses_unsafe_values_even_without_validation() {
        // Bypass `check_hosts` and call the renderer directly, the way a bug
        // elsewhere could.
        let cases: Vec<(&str, Mutation)> = vec![
            ("name", Box::new(|h| h.name = "a\nProxyCommand id".into())),
            (
                "hostname",
                Box::new(|h| h.hostname = "h\nProxyCommand id".into()),
            ),
            (
                "user",
                Box::new(|h| h.user = Some("u\rProxyCommand id".into())),
            ),
            (
                "identity file",
                Box::new(|h| h.identity_file = Some("k\nProxyCommand id".into())),
            ),
            (
                "local forward",
                Box::new(|h| h.local_forwards.push(forward(1, "d\nProxyCommand id", 2))),
            ),
            (
                "remote forward",
                Box::new(|h| h.remote_forwards.push(forward(1, "d\x1b[31m", 2))),
            ),
        ];
        for (field, mutate) in cases {
            let mut evil = host("evil", "evil.example.com");
            mutate(&mut evil);
            let mut out = String::new();
            match render_host(&mut out, &evil, &[]) {
                Err(ExportError::UnsafeValue { field: got, .. }) => assert_eq!(got, field),
                other => panic!("{field}: unexpected result {other:?}"),
            }
        }

        // An unsafe value in a jump host is caught when its hop is written.
        let mut jump = host("jump", "jump.example.com");
        jump.user = Some("u\nProxyCommand id".into());
        let web = host("web", "web.example.com");
        let mut out = String::new();
        assert!(matches!(
            render_host(&mut out, &web, &[&jump]),
            Err(ExportError::UnsafeValue {
                field: "jump host",
                ..
            })
        ));
    }

    #[test]
    fn unsafe_value_errors_name_the_host_with_control_characters_escaped() {
        let err = ExportError::UnsafeValue {
            host: "a\x1b[31mb".into(),
            field: "hostname",
        };
        let message = err.to_string();
        assert!(!message.contains('\x1b'), "{message}");
        assert!(message.contains("hostname"), "{message}");
        assert!(message.contains("cannot be written safely"), "{message}");
    }

    #[test]
    fn default_path_is_in_the_ssh_directory() {
        let env = fake_env(&[("HOME", abs("home/me").into_os_string())]);
        assert_eq!(
            default_export_path(Platform::Linux, &env).unwrap(),
            abs("home/me").join(".ssh").join("bifrost_config")
        );
        assert!(matches!(
            default_export_path(Platform::Linux, &fake_env(&[])),
            Err(ExportError::NoHome)
        ));
        let win = fake_env(&[("USERPROFILE", abs("Users/me").into_os_string())]);
        assert_eq!(
            default_export_path(Platform::Windows, &win).unwrap(),
            abs("Users/me").join(".ssh").join("bifrost_config")
        );
    }

    fn sample() -> Hosts {
        hosts(vec![host("web", "web.example.com")])
    }

    #[test]
    fn export_writes_the_file_and_creates_the_directory() {
        let dir = tempfile::tempdir().unwrap();
        let target = dir.path().join(".ssh").join("bifrost_config");
        export_to(&sample(), &target).unwrap();
        assert_eq!(
            fs::read_to_string(&target).unwrap(),
            render(&sample()).unwrap()
        );
        let leftovers: Vec<_> = fs::read_dir(target.parent().unwrap())
            .unwrap()
            .map(|e| e.unwrap().file_name())
            .collect();
        assert_eq!(leftovers.len(), 1, "{leftovers:?}");
    }

    #[test]
    fn export_replaces_a_previous_export() {
        let dir = tempfile::tempdir().unwrap();
        let target = dir.path().join("bifrost_config");
        export_to(&sample(), &target).unwrap();
        let mut updated = sample();
        updated.add(host("db", "db.example.com")).unwrap();
        export_to(&updated, &target).unwrap();
        let text = fs::read_to_string(&target).unwrap();
        assert!(text.contains("Host db\n") && text.contains("Host web\n"));
    }

    #[test]
    fn export_refuses_to_overwrite_files_it_did_not_generate() {
        let dir = tempfile::tempdir().unwrap();
        let target = dir.path().join("bifrost_config");
        fs::write(&target, "Host precious\n    HostName keep.example.com\n").unwrap();
        let err = export_to(&sample(), &target).unwrap_err();
        assert!(matches!(err, ExportError::NotGenerated(_)), "{err:?}");
        assert_eq!(
            fs::read_to_string(&target).unwrap(),
            "Host precious\n    HostName keep.example.com\n"
        );
    }

    #[test]
    fn export_never_writes_to_an_ssh_config_file() {
        let dir = tempfile::tempdir().unwrap();
        let config = dir.path().join("config");
        fs::write(&config, "Host mine\n").unwrap();
        for name in ["config", "CONFIG"] {
            let err = export_to(&sample(), &dir.path().join(name)).unwrap_err();
            assert!(
                matches!(err, ExportError::ProtectedTarget(_)),
                "{name}: {err:?}"
            );
        }
        assert_eq!(fs::read_to_string(&config).unwrap(), "Host mine\n");

        // Exporting next to it leaves it alone.
        export_to(&sample(), &dir.path().join("bifrost_config")).unwrap();
        assert_eq!(fs::read_to_string(&config).unwrap(), "Host mine\n");
    }

    #[test]
    fn a_failed_export_writes_nothing() {
        let dir = tempfile::tempdir().unwrap();
        let target = dir.path().join("bifrost_config");
        let mut hosts = sample();
        hosts.add(host("ok", "ok.example.com")).unwrap();
        // A directory in the way makes the final rename fail.
        fs::create_dir(&target).unwrap();
        assert!(export_to(&hosts, &target).is_err());
        assert!(target.is_dir());
    }

    #[cfg(unix)]
    #[test]
    fn exported_files_are_user_only() {
        use std::os::unix::fs::PermissionsExt;

        let dir = tempfile::tempdir().unwrap();
        let ssh_dir = dir.path().join(".ssh");
        let target = ssh_dir.join("bifrost_config");
        export_to(&sample(), &target).unwrap();
        let mode = |p: &Path| fs::metadata(p).unwrap().permissions().mode() & 0o777;
        assert_eq!(mode(&target), 0o600);
        assert_eq!(mode(&ssh_dir), 0o700);

        // Replacing a broader file makes it user-only again.
        fs::set_permissions(&target, fs::Permissions::from_mode(0o644)).unwrap();
        export_to(&sample(), &target).unwrap();
        assert_eq!(mode(&target), 0o600);
    }
}
